version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - enzo_uploads:/var/www/html/uploads
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: enzo_tech
      DB_USER: enzo
      DB_PASS: enzo_secret

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: enzo_tech
      MYSQL_USER: enzo
      MYSQL_PASSWORD: enzo_secret
      MYSQL_ROOT_PASSWORD: root_secret
    ports:
      - "3307:3306"
    volumes:
      - enzo_mysql:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database_lgpd.sql:/docker-entrypoint-initdb.d/02-lgpd.sql
      - ./database_v2.sql:/docker-entrypoint-initdb.d/03-v2.sql
      - ./database_indexes.sql:/docker-entrypoint-initdb.d/04-indexes.sql

volumes:
  enzo_mysql:
  enzo_uploads:
